import dotenv from 'dotenv';

dotenv.config();

export default {
  AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: process.env.AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT,
  AZURE_DOCUMENT_INTELLIGENCE_KEY: process.env.AZURE_DOCUMENT_INTELLIGENCE_KEY,
  AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
  AZURE_CONTAINER_NAME: process.env.AZURE_STORAGE_CONTAINER_NAME || 'documents',
  AZURE_CUSTOM_MODEL_ID: process.env.AZURE_CUSTOM_MODEL_ID || 'Silvi_Reader_Full_2.0'
};