services:
  - type: web
    name: invoice-processor-api
    runtime: node
    region: oregon # Change to your preferred region
    plan: free # Change to 'starter' or higher for production
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      # Database
      - key: DATABASE_URL
        sync: false # Set manually in Render dashboard
      # Client URL
      - key: CLIENT_URL
        sync: false # Your Vercel frontend URL
      - key: PRODUCTION_URL
        sync: false # Your custom domain if you have one
      # Azure Document Intelligence
      - key: AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT
        sync: false
      - key: AZURE_DOCUMENT_INTELLIGENCE_KEY
        sync: false
      - key: AZURE_CUSTOM_MODEL_ID
        value: Silvi_Reader_Full_2.0
      # Azure Storage
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false
      - key: AZURE_STORAGE_CONTAINER_NAME
        value: documents
      # Authentication
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      # Google OAuth (optional)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false # Should be https://your-api.onrender.com/auth/google/callback
    # Health check path
    healthCheckPath: /api/health